---
title: 'HW #4: Risk Prediction Index Critique'
author: "Gaea Daniel"
date: "February 22, 2017"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

# NRSG 741 Homework 4: Risk Prediction Index Critique
The observed prediction index is from an article entitled “Measuring cervical cancer risk: development and validation of the CARE Risky Sexual Behavior Index” (Reiter et al., 2008). This is not the first risky sexual behavior index, but according to the authors, none of the previous indices have been specific for cervical cancer. The predictor variables are as follows:
•	Age at first sexual intercourse
•	Number of sexual partners during lifetime
•	Any male sexual partners with history of sex with other men
•	Any male sexual partners with history of intravenous drug use
•	Any male sexual partners with history of sexually transmitted infection
•	History of sexual intercourse in exchange for money
•	Condom use frequency.

All of these predictor variables are appropriate, as they all look at sexual behavior. This can be considered the most important aspect of cervical cancer prediction because cervical cancer develops from persistent presence of certain strains of the sexually transmitted human papillomavirus (HPV). The length of time a person has been sexually active and exchange of money being the purpose for sex both increase the possibility more sexual partners, which increase the chances for exposure to HPV.  The male partner’s sexual history is relevant as well because their risky sexual behaviors can increase their exposure to HPV and, as a result, also increase the chances of exposure to HPV.

An important variable that could have been added are the same as the second and third variables related to the male sexual partners, but asked directly of the individual for whom the prediction index is targeting. Also, exchange for sexual intercourse should not be limited to money, but should be more inclusive by adding “services, goods, and drugs” or using “anything of value.” Furthermore, sexual partners should not be limited to males because Marrazzo et al. found that HPV transmission occurs between women having sex with women (1998), which the author acknowledges. 

The index was tested and validated using the Hosmer-Lemeshow test for goodness-of-fit. The authors did not perform an external validation. The most obvious limitation to generalization of the index was the lack of diversity within the tested population, with few women reporting the occurrence of sex for money or sex with men who have a history of sex with other men or intravenous drug use. Condom use was also proved difficult to measure because of marital status. The index was published in 2009. As the first of its kind, is appears to be a solid start to developing an index that can be relevant to today’s healthcare environment, perhaps in a gynecologist’s office. 

## References

Marrazzo, J. M., Koutsky, L. A., Stine, K. L., Kuypers, J. M., Grubert, T. A., Galloway, D. A., ... & Handsfield, H. H. (1998). Genital human papillomavirus infection in women who have sex with women. Journal of infectious diseases, 178(6), 1604-1609.

Reiter, P. L., Katz, M. L., Ferketich, A. K., Ruffin, M. T., & Paskett, E. D. (2009). Measuring cervical cancer risk: development and validation of the CARE Risky Sexual Behavior Index. Cancer Causes & Control, 20(10), 1865.
